nelmio_api_doc:
    documentation:
        info:
            title: My API
            description: This is an awesome API
            version: 1.0.0
    areas: # To filter the routes that are documented
        default:
            path_patterns: [ ^/api ]
