nelmio_api_doc:
    resource: ./routes/nelmio_api_doc.yaml
    prefix: /api/doc

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
